import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next js first demo project',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
    </>
  )
}
